name: Build Mythic
on:
  push:
    paths: &workflow_paths
      - '.github/workflows/build.yml'
      - 'Mythic.xcodeproj/**'
      - 'Mythic/**'
      - 'Packages/**'
      - 'scripts/**'
  pull_request:
    paths: *workflow_paths
  workflow_dispatch:

# cancel previous runs w/ same ref, save CI minutes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v5

    - uses: irgaly/xcode-cache@v1
      with:
        key: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
        restore-keys: xcode-cache-deriveddata-${{ github.workflow }}-
        
    - name: Core tests
      run: swift test --package-path Packages/GameHubCore
    - name: License check
      run: test -s LICENSE.md
    - run: |
        xcodebuild -scheme Mythic -configuration Debug \
          CODE_SIGNING_ALLOWED=NO \
          SWIFTLINT=NO \
          -parallel-testing-enabled YES \
          -jobs $(sysctl -n hw.ncpu) \
          -verbose
